sudo: required
dist: trusty
language: python
notifications:
  email: false
python:
  - "3.5"
before_install:
  - chmod +x .travis/install.sh
install:
  - "./.travis/install.sh"
script: python main.py test
#  - "./.travis/run.sh"
